//getInspection reducer actions
export const INSPECTION_CALL_ERROR = 'INSPECTION_CALL_ERROR';
export const INSPECTION_CALL_SUCCESS = 'INSPECTION_CALL_SUCCESS';
export const INSPECTION_CALL_LOADING = 'INSPECTION_CALL_LOADING';
//getCardex reducer actions
export const CARDEX_CALL_ERROR = 'CARDEX_CALL_ERROR';
export const CARDEX_CALL_SUCCESS = 'CARDEX_CALL_SUCCESS';
export const CARDEX_CALL_LOADING = 'CARDEX_CALL_LOADING';
//getLocalizationProduct reducer actions
export const LOCALIZATION_PRODUCT_CALL_ERROR = 'LOCALIZATION_PRODUCT_CALL_ERROR';
export const LOCALIZATION_PRODUCT_CALL_SUCCESS = 'LOCALIZATION_PRODUCT_CALL_SUCCESS';
export const LOCALIZATION_PRODUCT_CALL_LOADING = 'LOCALIZATION_PRODUCT_CALL_LOADING';
//getOnGoingMissions reducer actions
export const ONGOINGMISSIONS_CALL_ERROR = 'ONGOINGMISSIONS_CALL_ERROR';
export const ONGOINGMISSIONS_CALL_SUCCESS = 'ONGOINGMISSIONS_CALL_SUCCESS';
export const ONGOINGMISSIONS_CALL_LOADING = 'ONGOINGMISSIONS_CALL_LOADING';
export const ONGOINGMISSIONS_CALL_RESET = 'ONGOINGMISSIONS_CALL_RESET';
//getAddress reducer actions
export const ADDRESS_CALL_ERROR = 'ADDRESS_CALL_ERROR';
export const ADDRESS_CALL_SUCCESS = 'ADDRESS_CALL_SUCCESS';
export const ADDRESS_CALL_LOADING = 'ADDRESS_CALL_LOADING';
//Modal reducer actions
export const MODAL_VISIBLE = 'MODAL_VISIBLE';
//Login reducer actions
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FETCH_DATA_SUCCESS = 'LOGIN_FETCH_DATA_SUCCESS';
//Token reducer actions
export const TOKEN_LOAD_SUCCESS = 'TOKEN_LOAD_SUCCESS';
export const TOKEN_ERROR = 'TOKEN_ERROR';
export const TOKEN_VERIFY_SUCCESS = 'TOKEN_VERIFY_SUCCESS';
//getClientAddresses reducer actions
export const CLIENTADDRESSES_CALL_ERROR = 'CLIENTADDRESSES_CALL_ERROR';
export const CLIENTADDRESSES_CALL_SUCCESS = 'CLIENTADDRESSES_CALL_SUCCESS';
export const CLIENTADDRESSES_CALL_LOADING = 'CLIENTADDRESSES_CALL_LOADING';
//connectionCheck reducer actions
export const CONNECTED = 'CONNECTED';
//getProviderTodayMissions actions
export const PROVIDERTODAYMISSIONS_CALL_ERROR = 'PROVIDERTODAYMISSIONS_CALL_ERROR';
export const PROVIDERTODAYMISSIONS_CALL_LOADING = 'PROVIDERTODAYMISSIONS_CALL_LOADING';
export const PROVIDERTODAYMISSIONS_CALL_SUCCESS = 'PROVIDERTODAYMISSIONS_CALL_SUCCESS';
